name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry
        shell: bash

      - run: poetry install
        shell: bash

      - name: Publish package
        run: |
          poetry publish --build --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
        shell: bash